---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: proxysql
    tier: frontend
  name: proxysql
spec:
  ports:
  - name: proxysql-mysql
    port: 6033
    protocol: TCP
  - name: proxysql-admin
    port: 6032
    protocol: TCP
  - name: proxysql-web
    port: 6080
    protocol: TCP
  - name: proxysql-metrics
    port: 9170
    protocol: TCP
  selector:
    app: proxysql
    tier: frontend
  type: ClusterIP
